Sprint 4
ndronov/middle.messenger.praktikum.yandex pull request #5
Opened 2021-12-04 11:24 UTC by ndronov

2021-12-04 21:13 UTC, avdoshenkov approved these changes
Хорошая работа! 👍

Но надо перепроверить деплой, т.к. по адресу https://messenger-domain.herokuapp.com/sign-up у меня открывается только сообщение «Hello!»

2021-12-04 21:20 UTC, avdoshenkov requested changes
Всё-таки лучше доработать деплой в рамках проверки

2021-12-06 11:33 UTC, ndronov commented
> Всё-таки лучше доработать деплой в рамках проверки

доработал деплой

2021-12-07 10:34 UTC, avdoshenkov approved these changes
Отлично!

2021-12-07 11:19 UTC, merged